import React from 'react';
import UpdatedBanner from '@/components/shared/userShared/Banner/UpdatedBanner';
import ContactUs from '@/components/shared/userShared/ContactUs/ContactUs';
import FAQ from '@/components/shared/userShared/FAQ/FAQ';
import TradingAccounts from '@/components/shared/userShared/TradingAccounts/TradingAccounts';


export const metadata = {
    title: "Price Delivery -Home",
    description: "Generated by Tamzid",
};


const UserHome = () => {
    return (
        <>
             {/* <Banner /> */}
             <UpdatedBanner href="#apply"/>
            <TradingAccounts/>
            <ContactUs/>
            <FAQ/>
        </>
    );
};

export default UserHome;