import React from 'react';

export const metadata = {
    title: "Price Delivery -Home",
    description: "Generated by Tamzid",
  };

const Home = () => {
    return (
        <div>
            <h1>HomePage</h1>
        </div>
    );
};

export default Home;