import Banner from '@/components/shared/userShared/Banner/Banner';
import UpdatedBanner from '@/components/shared/userShared/Banner/UpdatedBanner';
import ContactUs from '@/components/shared/userShared/ContactUs/ContactUs';
import FAQ from '@/components/shared/userShared/FAQ/FAQ';
import TradingAccounts from '@/components/shared/userShared/TradingAccounts/TradingAccounts';
import React from 'react';

export const metadata = {
    title: "Price Delivery -Home",
    description: "Generated by Tamzid",
};

const Home = () => {
    return (
        <div className='xl:max-w-7xl lg:max-w-6xl md:max-w-3xl sm: max-w-sm mx-auto mt-[70px] '>
            {/* <Banner /> */}
            <UpdatedBanner href="#apply"/>
            <TradingAccounts/>
            <ContactUs/>
            <FAQ/>
        </div>
    );
};

export default Home;