import Banner from '@/components/shared/userShared/Banner/Banner';
import React from 'react';

export const metadata = {
    title: "Price Delivery -Home",
    description: "Generated by Tamzid",
};

const Home = () => {
    return (
        <div className='xl:max-w-7xl lg:max-w-6xl md:max-w-3xl sm: max-w-sm mx-auto mt-[70px]'>
            <Banner />
        </div>
    );
};

export default Home;